RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index]
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditClone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  has_many :post_subs

  has_many :subs,
           through: :post_subs

  belongs_to :author,
             class_name: :User,
             primary_key: :id,
             foreign_key: :user_id
end

RedditClone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  belongs_to :sub
  belongs_to :post
end

RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
             class_name: :User,
             primary_key: :id,
             foreign_key: :user_id

  has_many :post_subs

  has_many :posts,
           through: :post_subs
end

RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  password_digest :string           not null
#  username        :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :session_token, :password_digest, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password
  after_initialize :ensure_session_token

  has_many :subs

  has_many :posts

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token
    @current_user = user
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
    current_user = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = "Invalid credentials"
      redirect_to new_session_url
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end
end

RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <%= auth_token %>
        <input type="submit" value="Sign Out">
      </form>
    <% end %>

    <%= flash[:errors] if flash[:errors] %>

    <%= yield %>
  </body>
</html>

RedditClone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <%= auth_token %>
    <label>Title:
    <input type="text" name="post[title]" value="<%=@post.title%>">
    </label>
    <label>url:
    <input type="text" name="post[url]" value="<%=@post.url%>">
    </label>
    <label>content:
    <input type="body" name="post[content]" value="<%=@post.content%>">
    </label>

    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
        <label>
            <%= sub.title %>
            <input type="checkbox"
                value="<%= sub.id %>"
                name="post[sub_ids][]"
                <%= "checked" if @post.sub_ids.include?(sub.id)  %>
                >
        </label>
    <% end %>
    <input type="submit" value="Update Post">

</form>

RedditClone/app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%=posts_url%>" method="post">
    <%= auth_token %>
    <label>Title:
    <input type="text" name="post[title]" value="<%=@post.title%>">
    </label>
    <label>url:
    <input type="text" name="post[url]" value="<%=@post.url%>">
    </label>
    <label>content:
    <input type="body" name="post[content]" value="<%=@post.content%>">
    </label>

    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
        <label>
            <%= sub.title %>
            <input type="checkbox"
                value="<%= sub.id %>"
                name="post[sub_ids][]"
                <%= "checked" if @post.sub_ids.include?(sub.id)  %>
                >
        </label>
    <% end %>
    <input type="submit" value="Create Post">

</form>

RedditClone/app/views/posts/show.html.erb
<%= @post.title %>
<br>
<a href="<%= edit_post_url(@post) %>">Edit Post</a>
<h2>Subs</h2>

<ul>
<% @post.subs.each do |sub| %>
    <li><a href="<%= sub_url(sub)%>"><%= sub.title%></a></li>
<% end  %>
</ul>

RedditClone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <%= auth_token %>
    <label>
    Title
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>

    <label>
    Description
        <input type="body" name="sub[description]" value="<%= @sub.description %>">
    </label>
    <input type="submit" value="Update Sub">
</form>

RedditClone/app/views/subs/index.html.erb
<h1>Index of Subs</h1>

<a href="<%= new_sub_url %>"> Add Sub </a>

<ul>
    <% @subs.each do |sub| %>
        <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
    <% end %>
</ul>

RedditClone/app/views/subs/new.html.erb
<h1>Add Sub</h1>

<form action="<%= subs_url %>" method="post">
    <%= auth_token %>
    <label>
    Title
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>

    <label>
    Description
        <input type="body" name="sub[description]" value="<%= @sub.description %>">
    </label>
    <input type="submit" value="Add Sub">
</form>

RedditClone/app/views/subs/show.html.erb
<ul>
    <li><%= @sub.title %></li>
    <li><textarea cols="30" rows="10"><%= @sub.description %></textarea></li>
</ul>

<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a> | <a href="<%= subs_url %>">Index of Subs</a>
| <a href="<%= new_post_url %>">Add Post</a>

<ul>
    <% @sub.posts.each do |post| %>
        <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
    <% end %>
</ul>

RedditClone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
    <%= auth_token %>
    <label>
    Username
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>

    <label>
    Password
        <input type="password" name="user[password]" value="<%= @user.password %>">
    </label>
    
    <input type="submit" value="Sign Up">
</form>